## Basic Configuration

baseurl = "https://stas.vitko.me/"
builddrafts = false
canonifyurls = false
languageCode = "en-US"

contentdir = "content"
layoutdir = "layouts"
publishdir = "public"

author = "Stanislav Vitko"
title = "Stanislav Vitko"

theme = "hugo-goa"

## Hugo Built-in Features
#disqusShortname = "https-shenoybr-github-io-hugo-goa-demo" # Comment out to disable Disqus.
#googleAnalytics = "G-9MVZKPFT40"
enableRobotsTXT = true

## Site Settings
[params]
author = "Stanislav Vitko"
#intro = "intro data"
description = "Now @polysign."
authorimage = "me_02.jpg"
dateformat = "Jan 2, 2006"

## Site Meta Settings
[params.meta]
description = "Stanislav Vitko"
keywords = "vitko,stas,stan,stanislav"

## Social Accounts
[params.social]
github = "vistrcm"
linkedin = "vitkostanislav"
# instagram = "<username>"
# twitter = "<username>"
# facebook = "<username>"
# google = "<username>"
#stackoverflow = "<username>"
#email = "you@example.com"

## Extras
#[params.extra]
#copyright = "© 2016. Erlich Bachman. [Some Rights Reserved](http://creativecommons.org/licenses/by/3.0/)."
#poweredby = true
#hightlightjs = true

## Main Menu
[[menu.main]]
#     name = "blog"
#     weight = 100
#     identifier = "blog"
#     url = "/blog/"
#[[menu.main]]
    # name = "about"
    # identifier = "about"
    # weight = 200
    # url = "/about/"
# [[menu.main]]
#     name = "coderag"
#     identifier = "coderag"
#     weight = 300
#     url = "/coderag/"
[[menu.main]]
      name = "gpg: 0x48F22A464791F054"
      identifier = "gpg"
      url = "stasvitko.gpg"

[[menu.main]]
      name = "posts"
      identifier = "posts"
      url = "/posts/"

[deployment]
# By default, files are uploaded in an arbitrary order.
# Files that match the regular expressions in the "Order" list
# will be uploaded first, in the listed order.
# order = [".jpg$", ".gif$"]


[[deployment.targets]]
# An arbitrary name for this target.
name = "s3"

# S3; see https://gocloud.dev/howto/blob/#s3
# For S3-compatible endpoints, see https://gocloud.dev/howto/blob/#s3-compatible
URL = "s3://stas.vitko.me?region=us-west-1"

# If you are using a CloudFront CDN, deploy will invalidate the cache as needed.
cloudFrontDistributionID = "E1U5TMCSZPXS3Z"


[[deployment.targets]]
# An arbitrary name for this target.
name = "gs"
# The Go Cloud Development Kit URL to deploy to. Examples:
# GCS; see https://gocloud.dev/howto/blob/#gcs
URL = "gs://stas.vitko.me"


[[deployment.matchers]]
#  Cache static assets for 1 year.
pattern = "^.+\\.(js|css|svg|ttf)$"
cacheControl = "max-age=31536000, no-transform, public"
gzip = true

[[deployment.matchers]]
pattern = "^.+\\.(png|jpg)$"
cacheControl = "max-age=31536000, no-transform, public"
gzip = false

[[deployment.matchers]]
pattern = "^.+\\.(html|xml|json)$"
gzip = true
