## Basic Configuration

baseurl = "https://stas.vitko.me/"
builddrafts = false
canonifyurls = false
languageCode = "en-US"

contentdir = "content"
layoutdir = "layouts"
publishdir = "public"

author = "Stanislav Vitko"
title = "53 74 61 6e 69 73 6c 61 76 20 56 69 74 6b 6f"

theme = "hugo-goa"

## Hugo Built-in Features
#disqusShortname = "https-shenoybr-github-io-hugo-goa-demo" # Comment out to disable Disqus.
#googleAnalytics = "XYZ"
enableRobotsTXT = true

## Site Settings
[params]
author = "Stanislav Vitko"
#intro = "intro data"
description = "Now @griddynamics."
authorimage = "me_02.jpg"
dateformat = "Jan 2, 2006"

## Site Meta Settings
[params.meta]
description = "Stanislav Vitko"
keywords = "vitko,stas,stan,stanislav"

## Social Accounts
[params.social]
github = "vistrcm"
linkedin = "vitkostanislav"
# instagram = "<username>"
# twitter = "<username>"
# facebook = "<username>"
# google = "<username>"
#stackoverflow = "<username>"
#email = "you@example.com"

## Extras
#[params.extra]
#copyright = "© 2016. Erlich Bachman. [Some Rights Reserved](http://creativecommons.org/licenses/by/3.0/)."
#poweredby = true
#hightlightjs = true

## Main Menu
[[menu.main]]
#     name = "blog"
#     weight = 100
#     identifier = "blog"
#     url = "/blog/"
#[[menu.main]]
    # name = "about"
    # identifier = "about"
    # weight = 200
    # url = "/about/"
# [[menu.main]]
#     name = "coderag"
#     identifier = "coderag"
#     weight = 300
#     url = "/coderag/"
[[menu.main]]
      name = "gpg key"
      identifier = "gpg"
      url = "https://pgp.mit.edu/pks/lookup?op=get&search=0xF6D36FE96E6B5CBF"
